CREATE  NOTIFICATION INTEGRATION BANKING_SNOWPIPE_EVENT
ENABLED =TRUE
TYPE=QUEUE
NOTIFICATION_PROVIDER=AZURE_STORAGE_QUEUE
AZURE_STORAGE_QUEUE_PRIMARY_URI='https://snowflakeazuresnowpipe.queue.core.windows.net/azsnow-queue'
AZURE_TENANT_ID='7ecf1dcb-eca3-4727-8201-49cf4c94b669';

SHOW INTEGRATIONS;

--Drop integration MY_PIPE_EVENT;

desc NOTIFICATION INTEGRATION BANKING_SNOWPIPE_EVENT;
